ACCOUNTS = [ "GCMEY2I62TDZQAIA4GYWNUDPUKUPOT2O7GAXEM4GMCU5AGK5Y7ILEFQL", "GAXZWIIXDEESH7MVQNTHGC3OSQK4XSAPK27EXSAPXDQWQ2SMRWPEUTJE",]
[[PRINCIPALS]]
name = "Collin"

[[CURRENCIES]]
code = "BGDAO"
issuer = "GCMEY2I62TDZQAIA4GYWNUDPUKUPOT2O7GAXEM4GMCU5AGK5Y7ILEFQL"
name = "BlackGem Token"
desc = "BGDAO is a fully AI-powered token enabling decentralized governance and capital distribution for innovative projects."
image = "https://raw.githubusercontent.com/blackgem-ai/info/refs/heads/main/bgai_logo.png"

[DOCUMENTATION]
ORG_NAME = "BlackGem AI"
ORG_DBA = "BlackGem"
ORG_URL = "https://blackgemai.com"
ORG_LOGO = "https://raw.githubusercontent.com/blackgem-ai/info/refs/heads/main/bgai_logo.png"
ORG_GITHUB = "blackgem-ai"
ORG_DESCRIPTION = "BlackGem AI is a decentralized venture capital organization powered by artificial intelligence. Our mission is to leverage AI-driven strategies to identify and fund high-potential projects, fostering innovation and sustainable growth."
